import type { Metadata } from "next";
import { Sidbar } from "@/components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
      <section className="hidden border-r bg-muted/40 md:block">
        <Sidbar />
      </section>
      <section className="flex flex-col">{children}</section>
    </main>
  );
}
