import type { Metadata } from "next";
import { Inter, Acme } from "next/font/google";
import { Sidbar } from "@/components/sidebar/Sidebar";
import { Navbar } from "@/components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
const acme = Acme({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-acme",
  display: "block",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${acme.variable} ${inter.className}`}>
        <main className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
          <section className="hidden border-r bg-muted/40 md:block">
            <Sidbar />
          </section>
          <section className="flex flex-col">{children}</section>
        </main>
      </body>
    </html>
  );
}
